env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
rules:
  import/order:
    - error
    - groups: [builtin, external, internal]
      alphabetize: { order: 'asc', caseInsensitive: true }
      newlines-between: always
      pathGroups:
        - pattern: '{react*,redux*,react*/**}'
          group: external
          position: before
        - pattern: '{.,..}/**/*.{css,scss,sass}'
          group: internal
          position: after
      pathGroupsExcludedImportTypes: ['react', 'react-dom']
settings:
  react:
    version: detect
  import/resolver:
    typescript: true
    node: true
