on:
  push:
    branches:
    - main
    
jobs:
  deployment:
    name: "Deploy service via SSH"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "replnote-web-image"
      CONTAINER_NAME: "replnote-web-container"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pull repository
      shell: bash
      run: |
        echo '${{ secrets.OPENSSH_PRIVATE_KEY }}' | ssh -i /dev/stdin ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} -p ${{ vars.SSH_PORT }} <<EOF
          cd ${{ vars.SSH_PROJECT_DIRECTORY }}
          git pull origin main
        EOF
    - name: Build docker image
      shell: bash
      run: |
        echo '${{ secrets.OPENSSH_PRIVATE_KEY }}' | ssh -i /dev/stdin ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} -p ${{ vars.SSH_PORT }} <<EOF
          cd ${{ vars.SSH_PROJECT_DIRECTORY }}
          docker build -t $IMAGE_NAME .
        EOF
    - name: Run docker container
      shell: bash
      run: |
        echo '${{ secrets.OPENSSH_PRIVATE_KEY }}' | ssh -i /dev/stdin ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} -p ${{ vars.SSH_PORT }} <<EOF
          cd ${{ vars.SSH_PROJECT_DIRECTORY }}
          docker stop $CONTAINER_NAME
          docker run -d --rm --name $CONTAINER_NAME -v /etc/localtime:/etc/localtime:ro -p ${{ vars.PUBLISH_PORT }}:3000 $IMAGE_NAME
        EOF
