name: Deployer

on:
  push:
    branches:
    - main
    
jobs:
  deployment:
    name: "Deploy service via SSH"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "replnote-web-image"
      CONTAINER_NAME: "replnote-web-container"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test private key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.OPENSSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Hi"
    - name: Create private key file
      shell: bash
      run: |
        echo "PRIVATE_KEYFILE=$(mktemp)" >> $GITHUB_ENV
    - name: Write private key
      shell: bash
      run : |
        echo '${{ secrets.OPENSSH_PRIVATE_KEY }}' > $PRIVATE_KEYFILE
    - name: Pull repository
      shell: bash
      run: |
        ssh -i $PRIVATE_KEYFILE ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} <<EOF
          cd ${{ secrets.SSH_PROJECT_DIRECTORY }}
          git pull origin main
        EOF
    - name: Build docker image
      shell: bash
      run: |
        ssh -i $PRIVATE_KEYFILE ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} <<EOF
          cd ${{ secrets.SSH_PROJECT_DIRECTORY }}
          docker build -t $IMAGE_NAME .
        EOF
    - name: Run docker container
      shell: bash
      run: |
        ssh -i $PRIVATE_KEYFILE ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} <<EOF
          cd ${{ secrets.SSH_PROJECT_DIRECTORY }}
          docker stop $CONTAINER_NAME
          docker run -d --rm --name $CONTAINER_NAME -v /etc/localtime:/etc/localtime:ro -p ${{ secrets.PUBLISH_PORT }}:3000 $IMAGE_NAME
        EOF
    - name: Delete private key file
      shell: bash
      run: |
        rm -rf $PRIVATE_KEYFILE
